source 'http://rubygems.org'

gem 'jekyll'
gem 'haml'
gem 'rake'
gem 'RedCloth'
gem 'rdiscount'
gem 'sass'
gem 'coffee-script'
gem 'foreman'
gem 'rb-fsevent'
gem 'guard'
gem 'guard-livereload'
gem 'guard-jekyll'
gem 'jekyll-redirect-from'
gem 'rouge'
group :jekyll_plugins do
  # gem 'octopress-minify-html'
  gem 'jekyll-paginate'
end
