// Generated by CoffeeScript 1.4.0
console.log("Letsa go.")
jQuery(function() {
  $(window).resize();

  $.each($("a[id]"), function(index, ele) {
    return $(ele).click(function(e) {
      e.stopImmediatePropagation();
      return _gaq.push(["_trackEvent", "Links", "Clicked on " + e.target.id]);
    });
  });
  return $.each($("[data-time]"), function(index, ele) {
    return $(ele).html(prettyDate(new Date($(this).data("time"))));
  });
});
